# escape=`
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY /InternalAssets /ExternalAssets ${INSTALL_PATH}/

RUN `
`
`
<####################################################################################################################### `
`
	Install Sitecore `
`
------------------------------------------------------------------------------------------------------------------------#> `
`
	powershell -File (Join-Path $env:INSTALL_PATH 'XP0-SingleDeveloper.ps1') `
;